### ISSUE TITLE
Provi Health breaks Fresh Animations, or Custom Entity Model animations as a whole

### ISSUE THREAD

**Issue by kanguin2** [Provismet/ProviHealth#18]
### Type of Error

Incorrect Behaviour

### Mod List

- ProviHealth 1.2.1, 1.2.2, 1.2.3, for Fabric, Minecraft 1.20.1
- Entity Model Features 1.2.3 (coincidence wow) for Fabric Minecraft 1.20.1
- Fresh Animations resource pack, v. 1.8.1

### Description

I'm uncertain if this affects other CEM based resource packs, but this was tested with Fresh Animations.  When viewed directly to make the HUD pop up, mob animations distort for some reason.  This is most noticeable with villagers, whose eyebrows and mouths get crooked and their nose rotates 30 degrees left or right.  It's quite possible this could be resource-pack specific, but I wasn't able to confirm one way or another.
![image](https://github.com/Provismet/ProviHealth/assets/114624518/5d3c196e-6d04-4897-83a9-70c5dbddfb62)
![image](https://github.com/Provismet/ProviHealth/assets/114624518/3e2fc63b-53ad-4fce-804d-3e1acf71a48d)

### Mod Version

1.2.1-1.2.3

### Minecraft Version

1.20.1

### Mod Loader

Quilt

### Steps to Reproduce

```bash
1. Load Fabric or Quilt with necessary libraries to run Entity Model Features and ProviHealth.
2. Download Fresh Animations resource pack.
3. Boot Minecraft Fabric/Quilt with EMF and ProviHealth installed and enable Fresh Animations pack.
4. Find and look at a villager.
5. Watch their nose blow away in the wind.
```

**Comment by Provismet** [comment]
I can confirm that EMF as a whole does not break, because PHB is also used in my Monumenta modpack which uses EMF with a different texture pack. I believe this issue is specific to Fresh Animations.

Upon testing, it seems that the issue is only present when the HUD paperdoll is enabled. The paperdoll is rotated to a 150deg angle (which has to be done because otherwise you end up looking at the mob's back half the time). I believe that some of that rotation information is not being reset due to EMF or ETF adding extra parts, which is causing the issue.

I'll look into this and see if there's a workaround.

**Comment by Partonetrain** [comment]
It's not necessarily related to ETF. I'm seeing a side effect of this issue on the base of the dummy from [MmmMmmMmmMmm](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm).

**Comment by Partonetrain** [comment]
It's not necessarily related to ETF. I'm seeing a side effect of this issue on the dummy from [MmmMmmMmmMmm](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm). No matter which way you place it, it will face the angle of the paperdoll. It seems the changes are being propagated to the actual entity?

**Comment by Provismet** [comment]
> It seems the changes are being propagated to the actual entity?

Indeed. The paperdoll works by setting the rotation of the entity, rendering it, and then resetting them back to their original values.

The issue seems to be occuring with mobs that have unique overrides to setting their rotation.  
I'll look for an alternative method to rotate mobs without directly modifying the entity.

**Comment by Provismet** [comment]
This problem is now resolved and the fix will be a new compatibility setting in the options menu.

![image](https://github.com/Provismet/ProviHealth/assets/17149901/a5f53076-376b-4fd8-a266-34f3e35007b5)

The setting allows for the following options for your convenience:
- Standard (edits the mob's rotation directly, this method has been updated to break less mods and is the preferred method since the head and body can be done separately)
- Compatibility (rotates the display of the mob without touching its actual parameters, this works with Fresh Animations)
- None (removes the paperdoll entirely)

I'll push this with the next update alongside another (harder to notice) bugfix and some housekeeping.

**Comment by kanguin2** [comment]
Awesome, glad to see this fixed!  Your Health Bar mod is the most appealing one I could find.  Looking forward to the next update.
